name: Build Naqaa App APK

on:
  push:
    branches: [ main ] # يتم البناء تلقائياً عند رفع أي تحديث لفرع main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. سحب كود المشروع من الجيت هوب
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. إعداد بيئة فلاتر (Flutter) داخل خوادم جيت هوب
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # يمكنك تركها على الإصدار المستقر أو تحديثها
          channel: 'stable'

      # 3. جلب الحزم المطلوبة
      - name: Install dependencies
        run: flutter pub get

      # 4. بناء ملف الـ APK بنسخة الإصدار (Release)
      - name: Build Android APK
        run: flutter build apk --release

      # 5. رفع ملف الـ APK الناتج ليمكنك تحميله من الموقع
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naqaa-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
